package AdminClasses;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author gordo
 */
public class AdminMenu extends javax.swing.JFrame {

    /**
     * Creates new form AdminMenu
     */
    public AdminMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        myPanel = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        registerAdminButton = new javax.swing.JButton();
        registerManagerButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        updateAdminButton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        deleteAdminButton = new javax.swing.JButton();
        deleteManagerButton = new javax.swing.JButton();
        deleteAdvisorButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        restoreButton = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        blankButton = new javax.swing.JButton();
        backButton = new javax.swing.JButton();
        agentListButton = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administration Menu");
        setPreferredSize(new java.awt.Dimension(1200, 600));
        pack();
        setLocationRelativeTo(null);

        myPanel.setBackground(new java.awt.Color(153, 204, 255));
        myPanel.setPreferredSize(new java.awt.Dimension(1200, 600));

        jLabel6.setIcon(new javax.swing.ImageIcon("data/AirViaLogo.png")); // NOI18N
        jLabel6.setText("jLabel6");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Administration Menu");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("UPDATE USER DETAILS");

        registerAdminButton.setText("Register new System Administrator");

        registerManagerButton.setText("Register new Office Manager");

        jButton1.setText("Register new Sales Advisor");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("REGISTER NEW USER");

        updateAdminButton.setText("Update System Administrator details");

        jButton2.setText("Update Office Manager details");

        jButton3.setText("Update Sales Advisor Details");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("DATABASE MAINTAINENCE");

        deleteAdminButton.setText("Delete System Administrator");

        deleteManagerButton.setText("Delete Office Manager");

        deleteAdvisorButton.setText("Delete Sales Advisor");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("DELETE USER ACCOUNT");

        restoreButton.setText("RESTORE DATABASE");

        jButton4.setText("BACKUP DATABASE");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("OTHER");

        blankButton.setText("VIEW BLANK STOCK");
        blankButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blankButtonActionPerformed(evt);
            }
        });

        backButton.setText("BACK");

        agentListButton.setText("VIEW AGENT LIST");
        agentListButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agentListButtonActionPerformed(evt);
            }
        });

        jButton5.setText("VIEW TICKET TYPE LIST");

        javax.swing.GroupLayout myPanelLayout = new javax.swing.GroupLayout(myPanel);
        myPanel.setLayout(myPanelLayout);
        myPanelLayout.setHorizontalGroup(
                myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(myPanelLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(93, 93, 93)
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                        .addComponent(updateAdminButton)
                                                                        .addComponent(registerAdminButton))
                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                                .addGap(39, 39, 39)
                                                                                .addComponent(registerManagerButton))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                                                                                .addGap(31, 31, 31)
                                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                        .addComponent(jButton1)
                                                                        .addComponent(jButton3)
                                                                        .addComponent(deleteAdvisorButton)))
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addComponent(blankButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(agentListButton)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jButton5)
                                                                .addGap(43, 43, 43)))
                                                .addContainerGap(287, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(backButton)
                                                .addGap(55, 55, 55))
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addGap(380, 380, 380)
                                                                .addComponent(jLabel2))
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addGap(383, 383, 383)
                                                                .addComponent(jLabel3))
                                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                                .addGap(335, 335, 335)
                                                                .addComponent(jLabel1)))
                                                .addGap(0, 0, Short.MAX_VALUE))))
                        .addGroup(myPanelLayout.createSequentialGroup()
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(331, 331, 331)
                                                .addComponent(deleteAdminButton)
                                                .addGap(40, 40, 40)
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(deleteManagerButton)
                                                        .addComponent(jLabel5)))
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(468, 468, 468)
                                                .addComponent(restoreButton)
                                                .addGap(49, 49, 49)
                                                .addComponent(jButton4)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, myPanelLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(526, 526, 526))
        );
        myPanelLayout.setVerticalGroup(
                myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(myPanelLayout.createSequentialGroup()
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addComponent(jLabel6))
                                        .addGroup(myPanelLayout.createSequentialGroup()
                                                .addGap(31, 31, 31)
                                                .addComponent(backButton)
                                                .addGap(1, 1, 1)
                                                .addComponent(jLabel1)
                                                .addGap(30, 30, 30)
                                                .addComponent(jLabel3)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(registerAdminButton)
                                                        .addComponent(registerManagerButton)
                                                        .addComponent(jButton1))
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel2)
                                                .addGap(10, 10, 10)
                                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(updateAdminButton)
                                                        .addComponent(jButton2)
                                                        .addComponent(jButton3))))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(deleteAdminButton)
                                        .addComponent(deleteManagerButton)
                                        .addComponent(deleteAdvisorButton))
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton4)
                                        .addComponent(restoreButton))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(myPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(blankButton)
                                        .addComponent(agentListButton)
                                        .addComponent(jButton5))
                                .addContainerGap(150, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(myPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void blankButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void agentListButtonActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JButton agentListButton;
    private javax.swing.JButton backButton;
    private javax.swing.JButton blankButton;
    private javax.swing.JButton deleteAdminButton;
    private javax.swing.JButton deleteAdvisorButton;
    private javax.swing.JButton deleteManagerButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel myPanel;
    private javax.swing.JButton registerAdminButton;
    private javax.swing.JButton registerManagerButton;
    private javax.swing.JButton restoreButton;
    private javax.swing.JButton updateAdminButton;
    // End of variables declaration
}
